# fly.toml app configuration file generated for oban-example on 2023-10-31T13:48:34-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "oban-example"
primary_region = "bog"
kill_signal = "SIGTERM"
swap_size_mb = 512

[build]

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "oban-example.fly.dev"
  PORT = "8080"
  DNS_CLUSTER_QUERY = "oban-example.internal"
  RELEASE_COOKIE = "oban-example-cluster-cookie"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
